// 自动生成 1000+ 句生活英语数据库 
 
 const make = (arrCN, arrEN) => 
   arrCN.map((c, i) => ({ cn: c, en: arrEN[i] })); 
 
 const data = { 

日常问候: make( 
[
"你好","早上好","晚上好","你好吗","我很好","谢谢","不客气","再见","明天见","祝你开心",
"好久不见","慢一点说","请再说一遍","我听不懂","没关系","打扰一下","请等一下","没问题","当然可以","太好了",
"很高兴见到你","认识你很高兴","你叫什么名字","我叫...","你来自哪里","我来自中国","你多大了","我...岁了","你身体好吗","祝你健康"
], 
[
"Hello","Good morning","Good evening","How are you","I'm fine","Thank you","You're welcome","Goodbye","See you tomorrow","Have a nice day",
"Long time no see","Please speak slowly","Please say it again","I don't understand","It's okay","Excuse me","Please wait","No problem","Of course","That's great",
"Nice to meet you","I'm glad to meet you","What's your name","My name is...","Where are you from","I'm from China","How old are you","I'm... years old","How are you feeling","Wish you good health"
]
), 

 购物: [], 
 餐厅用餐: [], 
 旅行交通: [], 
 医院健康: [], 
 问路路牌: [], 
 银行支付: [], 
 电话沟通: [], 
 紧急求助: [], 
 社交聊天: [],
 咖啡店: [],
 家庭生活: [],
 职场用语: [],
 休闲娱乐: [] 
}; 
 
 
 // ⭐ 自动批量扩展句子（核心黑科技） 
 // 为每个分类定义不同的模板
 const categoryTemplates = {
   "购物": [
     ["这个多少钱", "How much is this"],
     ["有打折吗", "Is there a discount"],
     ["我可以试穿吗", "Can I try it on"],
     ["有大一点的尺码吗", "Do you have a larger size"],
     ["有小一点的尺码吗", "Do you have a smaller size"],
     ["我要这个", "I'll take this"],
     ["可以刷卡吗", "Can I pay by credit card"],
     ["可以用现金吗", "Can I pay in cash"],
     ["有发票吗", "Do you have a receipt"],
     ["可以退货吗", "Can I return it"],
     ["在哪里付款", "Where do I pay"],
     ["有其他颜色吗", "Do you have other colors"],
     ["这个质量怎么样", "How is the quality"],
     ["可以便宜一点吗", "Can you make it cheaper"],
     ["我在找一件外套", "I'm looking for a coat"],
     ["这个适合老年人吗", "Is this suitable for elderly people"],
     ["有保暖的衣服吗", "Do you have warm clothes"],
     ["这个是什么材质", "What material is this"],
     ["可以送货上门吗", "Can you deliver it"],
     ["什么时候到货", "When will it arrive"],
     ["这个有保修吗", "Does this have a warranty"],
     ["我想换一个", "I want to exchange it"],
     ["这个是最新款吗", "Is this the latest model"],
     ["有样品吗", "Do you have a sample"],
     ["这个怎么用", "How to use this"],
     ["有说明书吗", "Do you have instructions"],
     ["这个是中国制造吗", "Is this made in China"],
     ["有进口的吗", "Do you have imported ones"],
     ["这个重量是多少", "How much does this weigh"],
     ["可以帮我包装一下吗", "Can you wrap it for me"]
   ],
   "餐厅用餐": [
     ["请问有座位吗", "Do you have a table, please"],
     ["我要预订一个座位", "I'd like to book a table"],
     ["两个人的座位", "A table for two"],
     ["菜单在哪里", "Where is the menu"],
     ["有中文菜单吗", "Do you have a Chinese menu"],
     ["这个是什么菜", "What is this dish"],
     ["这个辣吗", "Is this spicy"],
     ["我不吃辣", "I don't eat spicy food"],
     ["我要一份米饭", "I'd like a bowl of rice"],
     ["我要一杯茶", "I'd like a cup of tea"],
     ["我要一杯咖啡", "I'd like a cup of coffee"],
     ["咖啡要加糖吗", "Would you like sugar in your coffee"],
     ["咖啡要加奶吗", "Would you like milk in your coffee"],
     ["这个菜多少钱", "How much is this dish"],
     ["可以打包吗", "Can I take it away"],
     ["打包盒多少钱", "How much is the takeaway box"],
     ["服务员", "Waiter/Waitress"],
     ["买单", "Check, please"],
     ["可以刷卡吗", "Can I pay by credit card"],
     ["可以用现金吗", "Can I pay in cash"],
     ["有发票吗", "Do you have a receipt"],
     ["这个菜太咸了", "This dish is too salty"],
     ["这个菜太甜了", "This dish is too sweet"],
     ["这个菜还没熟", "This dish is not cooked"],
     ["可以换一个吗", "Can I change it"],
     ["我想要餐具", "I need cutlery"],
     ["我想要餐巾纸", "I need napkins"],
     ["我想要酱油", "I need soy sauce"],
     ["我想要醋", "I need vinegar"],
     ["我想要辣椒酱", "I need chili sauce"]
   ],
   "旅行交通": [
     ["请问地铁站在哪里", "Excuse me, where is the subway station"],
     ["请问公交站在哪里", "Excuse me, where is the bus stop"],
     ["请问火车站在哪里", "Excuse me, where is the train station"],
     ["请问机场在哪里", "Excuse me, where is the airport"],
     ["去市中心怎么走", "How to get to the city center"],
     ["去医院怎么走", "How to get to the hospital"],
     ["去银行怎么走", "How to get to the bank"],
     ["去超市怎么走", "How to get to the supermarket"],
     ["去公园怎么走", "How to get to the park"],
     ["去博物馆怎么走", "How to get to the museum"],
     ["去图书馆怎么走", "How to get to the library"],
     ["去电影院怎么走", "How to get to the cinema"],
     ["去购物中心怎么走", "How to get to the shopping center"],
     ["去饭店怎么走", "How to get to the restaurant"],
     ["去酒店怎么走", "How to get to the hotel"],
     ["去学校怎么走", "How to get to the school"],
     ["去邮局怎么走", "How to get to the post office"],
     ["去警察局怎么走", "How to get to the police station"],
     ["去加油站怎么走", "How to get to the gas station"],
     ["去药店怎么走", "How to get to the pharmacy"],
     ["地铁多少钱", "How much is the subway"],
     ["公交车多少钱", "How much is the bus"],
     ["出租车起步价是多少", "What's the taxi fare start"],
     ["到那里需要多长时间", "How long does it take to get there"],
     ["下一班车什么时候来", "When does the next bus come"],
     ["地铁几点开始运营", "What time does the subway start operating"],
     ["地铁几点结束运营", "What time does the subway stop operating"],
     ["公交车几点开始运营", "What time does the bus start operating"],
     ["公交车几点结束运营", "What time does the bus stop operating"],
     ["我迷路了", "I'm lost"]
   ],
   "医院健康": [
     ["我不舒服", "I'm not feeling well"],
     ["我生病了", "I'm sick"],
     ["我发烧了", "I have a fever"],
     ["我感冒了", "I have a cold"],
     ["我咳嗽了", "I have a cough"],
     ["我头痛", "I have a headache"],
     ["我肚子痛", "I have a stomachache"],
     ["我牙痛", "I have a toothache"],
     ["我耳朵痛", "I have an earache"],
     ["我眼睛痛", "I have an eyeache"],
     ["我喉咙痛", "I have a sore throat"],
     ["我背痛", "I have a backache"],
     ["我关节痛", "I have joint pain"],
     ["我肌肉痛", "I have muscle pain"],
     ["我头晕", "I feel dizzy"],
     ["我恶心", "I feel nauseous"],
     ["我呕吐了", "I vomited"],
     ["我拉肚子了", "I have diarrhea"],
     ["我便秘了", "I have constipation"],
     ["我失眠了", "I have insomnia"],
     ["我感到疲劳", "I feel tired"],
     ["我感到虚弱", "I feel weak"],
     ["我感到焦虑", "I feel anxious"],
     ["我感到抑郁", "I feel depressed"],
     ["我需要看医生", "I need to see a doctor"],
     ["我需要预约医生", "I need to make an appointment with a doctor"],
     ["请问医生在哪里", "Excuse me, where is the doctor"],
     ["请问护士在哪里", "Excuse me, where is the nurse"],
     ["请问药房在哪里", "Excuse me, where is the pharmacy"],
     ["请问挂号处在哪里", "Excuse me, where is the registration desk"]
   ],
   "问路路牌": [
     ["请问怎么走", "Excuse me, how to get there"],
     ["这是哪里", "Where is this"],
     ["附近有超市吗", "Is there a supermarket nearby"],
     ["附近有餐厅吗", "Is there a restaurant nearby"],
     ["附近有医院吗", "Is there a hospital nearby"],
     ["附近有银行吗", "Is there a bank nearby"],
     ["附近有邮局吗", "Is there a post office nearby"],
     ["附近有药店吗", "Is there a pharmacy nearby"],
     ["附近有公园吗", "Is there a park nearby"],
     ["附近有酒店吗", "Is there a hotel nearby"],
     ["附近有地铁站吗", "Is there a subway station nearby"],
     ["附近有公交站吗", "Is there a bus stop nearby"],
     ["附近有火车站吗", "Is there a train station nearby"],
     ["附近有机场吗", "Is there an airport nearby"],
     ["附近有购物中心吗", "Is there a shopping center nearby"],
     ["附近有电影院吗", "Is there a cinema nearby"],
     ["附近有博物馆吗", "Is there a museum nearby"],
     ["附近有图书馆吗", "Is there a library nearby"],
     ["附近有学校吗", "Is there a school nearby"],
     ["附近有警察局吗", "Is there a police station nearby"],
     ["左边", "Left"],
     ["右边", "Right"],
     ["直走", "Go straight"],
     ["左转", "Turn left"],
     ["右转", "Turn right"],
     ["过马路", "Cross the road"],
     ["在第一个路口", "At the first intersection"],
     ["在第二个路口", "At the second intersection"],
     ["在第三个路口", "At the third intersection"],
     ["就在前面", "Just ahead"]
   ],
   "银行支付": [
     ["我要开户", "I want to open an account"],
     ["我要存钱", "I want to deposit money"],
     ["我要取钱", "I want to withdraw money"],
     ["我要转账", "I want to transfer money"],
     ["我要换汇", "I want to exchange currency"],
     ["我要查询余额", "I want to check the balance"],
     ["我要打印对账单", "I want to print a statement"],
     ["我要挂失银行卡", "I want to report a lost bank card"],
     ["我要补办银行卡", "I want to reissue a bank card"],
     ["我要修改密码", "I want to change my password"],
     ["我要开通网银", "I want to open online banking"],
     ["我要开通手机银行", "I want to open mobile banking"],
     ["我要申请信用卡", "I want to apply for a credit card"],
     ["我要申请贷款", "I want to apply for a loan"],
     ["贷款利率是多少", "What's the loan interest rate"],
     ["存款利率是多少", "What's the deposit interest rate"],
     ["活期存款", "Current deposit"],
     ["定期存款", "Fixed deposit"],
     ["定期存款多长时间", "How long is the fixed deposit"],
     ["定期存款可以提前取吗", "Can fixed deposits be withdrawn early"],
     ["提前取款利息怎么算", "How is the interest calculated for early withdrawal"],
     ["转账需要手续费吗", "Is there a fee for transferring money"],
     ["转账手续费是多少", "What's the transfer fee"],
     ["转账多久到账", "How long does it take for the transfer to arrive"],
     ["换汇的汇率是多少", "What's the exchange rate"],
     ["我要换美元", "I want to exchange for US dollars"],
     ["我要换欧元", "I want to exchange for euros"],
     ["我要换英镑", "I want to exchange for pounds"],
     ["我要换日元", "I want to exchange for Japanese yen"],
     ["我要换韩元", "I want to exchange for Korean won"]
   ],
   "电话沟通": [
     ["喂，你好", "Hello"],
     ["请问你是哪位", "Who is speaking, please"],
     ["我想找...", "I want to speak to..."],
     ["请稍等", "Please hold on"],
     ["他不在", "He is not in"],
     ["请留言", "Please leave a message"],
     ["我会让他回电话", "I'll ask him to call back"],
     ["电话号码是多少", "What's the phone number"],
     ["打错了", "Wrong number"],
     ["再见", "Goodbye"],
     ["你好，我是...", "Hello, this is..."],
     ["请问您是...", "May I ask if you are..."],
     ["我能和...说话吗", "May I speak to..."],
     ["他什么时候回来", "When will he come back"],
     ["请告诉他...", "Please tell him that..."],
     ["我的电话号码是...", "My phone number is..."],
     ["我会再打过来", "I'll call back later"],
     ["请问您贵姓", "May I have your name"],
     ["很高兴认识你", "Nice to meet you"],
     ["请问有什么事吗", "May I help you"],
     ["请问您找哪位", "Who are you looking for"],
     ["请稍等一下", "Just a moment, please"],
     ["他正在忙", "He is busy right now"],
     ["他正在开会", "He is in a meeting"],
     ["他正在吃饭", "He is eating"],
     ["他正在睡觉", "He is sleeping"],
     ["他正在路上", "He is on his way"],
     ["他很快就回来", "He will be back soon"],
     ["请留下您的联系方式", "Please leave your contact information"],
     ["我会转告他", "I'll let him know"]
   ],
   "紧急求助": [
     ["救命", "Help"],
     ["报警", "Call the police"],
     ["叫救护车", "Call an ambulance"],
     ["叫消防车", "Call the fire department"],
     ["我迷路了", "I'm lost"],
     ["我的钱包丢了", "I lost my wallet"],
     ["我的手机丢了", "I lost my phone"],
     ["我需要帮助", "I need help"],
     ["有人吗", "Is anyone there"],
     ["请帮帮我", "Please help me"],
     ["着火了", "There's a fire"],
     ["有小偷", "There's a thief"],
     ["有人受伤了", "Someone is injured"],
     ["我受伤了", "I'm injured"],
     ["我生病了", "I'm sick"],
     ["我呼吸困难", "I'm having trouble breathing"],
     ["我心脏不舒服", "I'm having heart problems"],
     ["我头晕", "I'm dizzy"],
     ["我摔倒了", "I fell down"],
     ["我被车撞了", "I was hit by a car"],
     ["我的车坏了", "My car broke down"],
     ["我的车没油了", "My car ran out of gas"],
     ["我的车胎爆了", "My tire blew out"],
     ["我被困住了", "I'm trapped"],
     ["我找不到我的家人", "I can't find my family"],
     ["我找不到我的宠物", "I can't find my pet"],
     ["有人在跟踪我", "Someone is following me"],
     ["有人在骚扰我", "Someone is harassing me"],
     ["我感到害怕", "I'm scared"],
     ["我需要警察", "I need the police"]
   ],
   "社交聊天": [
    ["你好吗", "How are you"],
    ["我很好", "I'm fine"],
    ["最近怎么样", "How have you been lately"],
    ["一切都好", "Everything is fine"],
    ["还不错", "Not bad"],
    ["一般般", "Just so so"],
    ["不太好", "Not very good"],
    ["天气真好", "It's a nice day"],
    ["今天很热", "It's hot today"],
    ["今天很冷", "It's cold today"],
    ["今天下雨", "It's raining today"],
    ["今天晴天", "It's sunny today"],
    ["今天多云", "It's cloudy today"],
    ["今天有风", "It's windy today"],
    ["今天下雪", "It's snowing today"],
    ["你去哪里了", "Where have you been"],
    ["你在做什么", "What are you doing"],
    ["你喜欢什么", "What do you like"],
    ["你不喜欢什么", "What don't you like"],
    ["你有什么爱好", "What are your hobbies"],
    ["你喜欢运动吗", "Do you like sports"],
    ["你喜欢音乐吗", "Do you like music"],
    ["你喜欢电影吗", "Do you like movies"],
    ["你喜欢读书吗", "Do you like reading"],
    ["你喜欢旅行吗", "Do you like traveling"],
    ["你去过哪里", "Where have you been"],
    ["你想去哪里", "Where do you want to go"],
    ["你吃了吗", "Have you eaten"],
    ["你睡得好吗", "Did you sleep well"],
    ["你感觉怎么样", "How do you feel"]
  ],
  "咖啡店": [
    ["我想要一杯咖啡", "I'd like a cup of coffee"],
    ["可以给我一杯豆奶拿铁吗", "Can I get a latte with soy milk"],
    ["今天有什么推荐吗", "What do you recommend today"],
    ["我今天想换点新的", "I'll try something new today"],
    ["这个饮料甜吗", "Is this drink sweet"],
    ["我想要一杯美式咖啡", "I'd like an Americano"],
    ["我想要一杯卡布奇诺", "I'd like a cappuccino"],
    ["我想要一杯摩卡", "I'd like a mocha"],
    ["我想要一杯热巧克力", "I'd like a hot chocolate"],
    ["我想要一杯茶", "I'd like a cup of tea"],
    ["我想要一杯冰咖啡", "I'd like an iced coffee"],
    ["我想要一杯冰茶", "I'd like an iced tea"],
    ["可以加奶吗", "Can I have milk"],
    ["可以加糖吗", "Can I have sugar"],
    ["可以加蜂蜜吗", "Can I have honey"],
    ["可以加肉桂吗", "Can I have cinnamon"],
    ["可以加香草糖浆吗", "Can I have vanilla syrup"],
    ["可以加焦糖糖浆吗", "Can I have caramel syrup"],
    ["可以加薄荷糖浆吗", "Can I have mint syrup"],
    ["可以加榛子糖浆吗", "Can I have hazelnut syrup"],
    ["可以加杏仁糖浆吗", "Can I have almond syrup"],
    ["可以加椰子糖浆吗", "Can I have coconut syrup"],
    ["可以加覆盆子糖浆吗", "Can I have raspberry syrup"],
    ["可以加蓝莓糖浆吗", "Can I have blueberry syrup"],
    ["可以加草莓糖浆吗", "Can I have strawberry syrup"],
    ["可以加巧克力糖浆吗", "Can I have chocolate syrup"],
    ["可以加香草粉吗", "Can I have vanilla powder"],
    ["可以加可可粉吗", "Can I have cocoa powder"],
    ["可以加肉桂粉吗", "Can I have cinnamon powder"],
    ["可以加豆蔻粉吗", "Can I have nutmeg powder"],
    ["可以加姜粉吗", "Can I have ginger powder"],
    ["可以加辣椒吗", "Can I have chili"],
    ["可以加柠檬吗", "Can I have lemon"],
    ["可以加橙子吗", "Can I have orange"],
    ["可以加苹果吗", "Can I have apple"],
    ["可以加香蕉吗", "Can I have banana"],
    ["可以加草莓吗", "Can I have strawberry"],
    ["可以加蓝莓吗", "Can I have blueberry"],
    ["可以加覆盆子吗", "Can I have raspberry"],
    ["可以加芒果吗", "Can I have mango"],
    ["可以加菠萝吗", "Can I have pineapple"],
    ["可以加猕猴桃吗", "Can I have kiwi"],
    ["可以加葡萄吗", "Can I have grape"],
    ["可以加樱桃吗", "Can I have cherry"],
    ["可以加桃子吗", "Can I have peach"],
    ["可以加梨吗", "Can I have pear"],
    ["可以加李子吗", "Can I have plum"],
    ["可以加杏子吗", "Can I have apricot"],
    ["可以加石榴吗", "Can I have pomegranate"],
    ["可以加西瓜吗", "Can I have watermelon"]
  ],
  "家庭生活": [
    ["晚饭马上好了", "Dinner will be ready in a minute"],
    ["别忘了关灯", "Don't forget to turn off the lights"],
    ["作业写完了吗", "Did you finish your homework yet"],
    ["把鞋子脱了", "Take off your shoes"],
    ["洗手吃饭", "Wash your hands for dinner"],
    ["该睡觉了", "It's time to go to bed"],
    ["早上好，该起床了", "Good morning, it's time to get up"],
    ["今天天气怎么样", "How's the weather today"],
    ["记得带伞", "Remember to bring an umbrella"],
    ["记得带外套", "Remember to bring a jacket"],
    ["记得带钥匙", "Remember to bring your keys"],
    ["记得带手机", "Remember to bring your phone"],
    ["记得带钱包", "Remember to bring your wallet"],
    ["记得带身份证", "Remember to bring your ID"],
    ["记得带眼镜", "Remember to bring your glasses"],
    ["记得带帽子", "Remember to bring your hat"],
    ["记得带手套", "Remember to bring your gloves"],
    ["记得带围巾", "Remember to bring your scarf"],
    ["记得带口罩", "Remember to bring your mask"],
    ["记得带纸巾", "Remember to bring tissues"],
    ["记得带充电宝", "Remember to bring a power bank"],
    ["记得带充电器", "Remember to bring a charger"],
    ["记得带耳机", "Remember to bring headphones"],
    ["记得带笔记本", "Remember to bring a notebook"],
    ["记得带笔", "Remember to bring a pen"],
    ["记得带水杯", "Remember to bring a water bottle"],
    ["记得带药", "Remember to bring medicine"],
    ["记得带零食", "Remember to bring snacks"],
    ["记得带水果", "Remember to bring fruit"],
    ["记得带饮料", "Remember to bring drinks"],
    ["记得带相机", "Remember to bring a camera"],
    ["记得带三脚架", "Remember to bring a tripod"],
    ["记得带背包", "Remember to bring a backpack"],
    ["记得带手提包", "Remember to bring a handbag"],
    ["记得带公文包", "Remember to bring a briefcase"],
    ["记得带钥匙包", "Remember to bring a keychain"],
    ["记得带名片夹", "Remember to bring a business card holder"],
    ["记得带眼镜盒", "Remember to bring a glasses case"],
    ["记得带手机壳", "Remember to bring a phone case"],
    ["记得带手表", "Remember to bring a watch"],
    ["记得带项链", "Remember to bring a necklace"],
    ["记得带手链", "Remember to bring a bracelet"],
    ["记得带耳环", "Remember to bring earrings"],
    ["记得带戒指", "Remember to bring a ring"],
    ["记得带腰带", "Remember to bring a belt"],
    ["记得带袜子", "Remember to bring socks"],
    ["记得带内衣", "Remember to bring underwear"],
    ["记得带睡衣", "Remember to bring pajamas"],
    ["记得带拖鞋", "Remember to bring slippers"],
    ["记得带浴袍", "Remember to bring a bathrobe"]
  ],
  "职场用语": [
    ["早上好，同事们", "Good morning, everyone"],
    ["今天有什么任务", "What tasks do we have today"],
    ["这个项目进展如何", "How is this project going"],
    ["我们需要在周五前完成", "We need to finish by Friday"],
    ["可以帮我一下吗", "Can you help me with this"],
    ["我需要你的意见", "I need your opinion"],
    ["这个想法很好", "That's a great idea"],
    ["我们可以这样做", "We can do it this way"],
    ["让我们开会讨论", "Let's have a meeting to discuss"],
    ["会议在几点开始", "What time does the meeting start"],
    ["会议在哪里举行", "Where is the meeting held"],
    ["请准备好会议材料", "Please prepare the meeting materials"],
    ["请准时参加会议", "Please attend the meeting on time"],
    ["会议议程是什么", "What's the meeting agenda"],
    ["我来做会议记录", "I'll take meeting notes"],
    ["请发送会议纪要", "Please send the meeting minutes"],
    ["我们需要做什么", "What do we need to do"],
    ["我们的目标是什么", "What's our goal"],
    ["我们的计划是什么", "What's our plan"],
    ["我们的预算是多少", "What's our budget"],
    ["我们的时间表是什么", "What's our timeline"],
    ["我们的截止日期是什么", "What's our deadline"],
    ["我们的优先级是什么", "What's our priority"],
    ["我们的资源是什么", "What's our resource"],
    ["我们的团队成员有谁", "Who are our team members"],
    ["我们的客户是谁", "Who are our clients"],
    ["我们的合作伙伴是谁", "Who are our partners"],
    ["我们的竞争对手是谁", "Who are our competitors"],
    ["我们的市场定位是什么", "What's our market position"],
    ["我们的营销策略是什么", "What's our marketing strategy"],
    ["我们的销售目标是什么", "What's our sales target"],
    ["我们的客户满意度如何", "How is our customer satisfaction"],
    ["我们的产品质量如何", "How is our product quality"],
    ["我们的服务质量如何", "How is our service quality"],
    ["我们的创新能力如何", "How is our innovation capability"],
    ["我们的团队合作如何", "How is our team collaboration"],
    ["我们的沟通效率如何", "How is our communication efficiency"],
    ["我们的工作环境如何", "How is our work environment"],
    ["我们的工作氛围如何", "How is our work atmosphere"],
    ["我们的工作压力如何", "How is our work pressure"],
    ["我们的工作满意度如何", "How is our job satisfaction"],
    ["我们的职业发展如何", "How is our career development"],
    ["我们的培训机会如何", "How are our training opportunities"],
    ["我们的福利政策如何", "How are our benefits policies"],
    ["我们的企业文化如何", "How is our corporate culture"],
    ["我们的社会责任如何", "How is our social responsibility"],
    ["我们的未来发展如何", "How is our future development"],
    ["我们的核心价值观是什么", "What are our core values"],
    ["我们的使命是什么", "What is our mission"],
    ["我们的愿景是什么", "What is our vision"]
  ],
  "休闲娱乐": [
    ["你喜欢什么运动", "What sports do you like"],
    ["你喜欢看电影吗", "Do you like watching movies"],
    ["你喜欢听音乐吗", "Do you like listening to music"],
    ["你喜欢读书吗", "Do you like reading books"],
    ["你喜欢旅行吗", "Do you like traveling"],
    ["你喜欢爬山吗", "Do you like climbing mountains"],
    ["你喜欢游泳吗", "Do you like swimming"],
    ["你喜欢钓鱼吗", "Do you like fishing"],
    ["你喜欢露营吗", "Do you like camping"],
    ["你喜欢烧烤吗", "Do you like barbecuing"],
    ["你喜欢野餐吗", "Do you like picnicking"],
    ["你喜欢骑自行车吗", "Do you like riding a bike"],
    ["你喜欢散步吗", "Do you like walking"],
    ["你喜欢跑步吗", "Do you like running"],
    ["你喜欢瑜伽吗", "Do you like yoga"],
    ["你喜欢冥想吗", "Do you like meditating"],
    ["你喜欢跳舞吗", "Do you like dancing"],
    ["你喜欢唱歌吗", "Do you like singing"],
    ["你喜欢绘画吗", "Do you like painting"],
    ["你喜欢摄影吗", "Do you like photography"],
    ["你喜欢烹饪吗", "Do you like cooking"],
    ["你喜欢烘焙吗", "Do you like baking"],
    ["你喜欢园艺吗", "Do you like gardening"],
    ["你喜欢养宠物吗", "Do you like keeping pets"],
    ["你喜欢玩游戏吗", "Do you like playing games"],
    ["你喜欢下棋吗", "Do you like playing chess"],
    ["你喜欢打牌吗", "Do you like playing cards"],
    ["你喜欢打麻将吗", "Do you like playing mahjong"],
    ["你喜欢打台球吗", "Do you like playing billiards"],
    ["你喜欢打乒乓球吗", "Do you like playing table tennis"],
    ["你喜欢打羽毛球吗", "Do you like playing badminton"],
    ["你喜欢打篮球吗", "Do you like playing basketball"],
    ["你喜欢踢足球吗", "Do you like playing football"],
    ["你喜欢打排球吗", "Do you like playing volleyball"],
    ["你喜欢打网球吗", "Do you like playing tennis"],
    ["你喜欢打高尔夫球吗", "Do you like playing golf"],
    ["你喜欢打保龄球吗", "Do you like playing bowling"],
    ["你喜欢打棒球吗", "Do you like playing baseball"],
    ["你喜欢打橄榄球吗", "Do you like playing rugby"],
    ["你喜欢打曲棍球吗", "Do you like playing hockey"],
    ["你喜欢打手球吗", "Do you like playing handball"],
    ["你喜欢打垒球吗", "Do you like playing softball"],
    ["你喜欢打板球吗", "Do you like playing cricket"],
    ["你喜欢打马球吗", "Do you like playing polo"],
    ["你喜欢打槌球吗", "Do you like playing croquet"],
    ["你喜欢打沙狐球吗", "Do you like playing shuffleboard"],
    ["你喜欢打冰球吗", "Do you like playing ice hockey"],
    ["你喜欢打长曲棍球吗", "Do you like playing lacrosse"],
    ["你喜欢打壁球吗", "Do you like playing squash"],
    ["你喜欢打网球吗", "Do you like playing tennis"]
  ]
};
 
 // 使用每个分类的独特模板句子
Object.keys(data).forEach(key=>{ 
  if(data[key].length===0){ 
    const templates = categoryTemplates[key] || [
      ["我想要这个", "I'd like this"],
      ["多少钱", "How much is it"],
      ["请帮帮我", "Please help me"],
      ["可以吗", "Is it OK"],
      ["在哪里", "Where is it"]
    ];
    
    // 只添加独特的模板句子，不重复
    templates.forEach(t => {
      data[key].push({ 
        cn: t[0], 
        en: t[1] 
      }); 
    });
  } 
}); 
 
 if (typeof window !== 'undefined') {
  window.data = data;
} else {
  module.exports = data;
}